### ISSUE TITLE
Travis build problems.

### ISSUE THREAD

**Issue by PiotrJustyna** [PiotrJustyna/zero#2]
# Problem:

Travis build is currently permanently broken because of a missing dependency which is blacklisted by the CI server. I logged a [defect](https://github.com/travis-ci/apt-package-whitelist/issues/2721) yesterday and it is already picked up by Travis maintainers, so I hope it should get resolved soon.
# Details:

The build (depending on GPipe libraries) requires `Xxf86vm` library to be installed. When I add this library to the list of build dependencies (the lib is `libXxf86vm-dev`), Travis complains that the package cannot be installed as it's not whitelisted. This permanently stops my GPipe-dependent application from building correctly.
# Resolution

I'm currently waiting for Travis maintainers to whitelist this library. As soon as this is done, my builds should start working.

**Comment by PiotrJustyna** [comment]
I made the project build again in the Travis environment. The solution is quite hacky, but works :smile: Also, updated the defect I raised initially.

**Comment by PiotrJustyna** [comment]
If anybody is interested, this is a snapshot of the `.travis.yml` file at the time the build started working.:

```
cache:
  directories:
  - $HOME/.stack

matrix:
    include:
        - env: CABALVER=1.22 GHCVER=7.10.3
          addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.3, freeglut3-dev], sources: [hvr-ghc]}}

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - sudo add-apt-repository ppa:team-xbmc/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install libXxf86vm-dev
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack setup

script:
    - stack build
    - stack test
```
